Array Indexing
1. NUMPY INDEXING and SLICING OF VECTORES
2. NUMPY INDEXING AND SLICING OF MATRIX
3. BOOLEAN INDEXING

In [1]:
import numpy as np

NUMPY INDEXING and SLICING OF VECTORES

In [2]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr_slice = arr[1:10]
arr_slice

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

NUMPY INDEXING AND SLICING OF MATRIX

In [4]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [5]:
arr[0]

array([1, 2, 3, 4, 5])

In [6]:
arr[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
arr[0,4]

np.int64(5)

In [8]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [9]:
arr[2:6,2:6]

array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25],
       [28, 29, 30]])

In [10]:
arr[3:6,3:6]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [11]:
arr[:,4]

array([ 5, 10, 15, 20, 25, 30])

BOOLEAN INDEXING

In [13]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
bool_index = arr%2 == 0
bool_index

array([ True,  True,  True,  True,  True])

In [18]:
arr = arr[bool_index]
arr

array([ 2,  4,  6,  8, 10])