ARRAY OPRATIONS
1. Arithmetic Oprations
2. Broadcasting
3. Deep and Shallow copy
4. Matrix Oprations


Advance Array Manipulation
1. Stacking Array
2. Splitting Array

In [60]:
import numpy as np

1. Arithmetic Oprations

In [61]:
arr1 = np.arange(1,6)
arr1

array([1, 2, 3, 4, 5])

In [62]:
arr2 = np.arange(6,11)
arr2

array([ 6,  7,  8,  9, 10])

In [63]:
sum = arr1 + arr2
sum

array([ 7,  9, 11, 13, 15])

In [64]:
sub = arr2-arr1
sub

array([5, 5, 5, 5, 5])

In [65]:
mul = arr1*arr2
mul

array([ 6, 14, 24, 36, 50])

In [66]:
div1 = arr2/arr1
div1

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [67]:
div2 = arr1/arr2
div2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [68]:
fdiv = arr2//arr1
fdiv

array([6, 3, 2, 2, 2])

In [69]:
power = arr1**arr2
power

array([      1,     128,    6561,  262144, 9765625])

2. Broadcasting

In [70]:
l = [10,20,30,40]
l

[10, 20, 30, 40]

In [71]:
arr = np.array(l)
arr

array([10, 20, 30, 40])

In [72]:
arr+10

array([20, 30, 40, 50])

In [73]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [74]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [75]:
arr2 = arr2[0:2]+10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [76]:
arr2 = arr2[0:2,3:5]+10
arr2

array([[24, 25],
       [29, 30]])

3. Deep and Shallow copy

In [77]:
arr3 = np.arange(1,21)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [78]:
slice = arr3[:5]
slice = slice*10
slice

array([10, 20, 30, 40, 50])

In [79]:
arr3 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [80]:
arr4 = arr3.copy()
arr4[0] = 99

In [81]:
arr4

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [82]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

4. Matrix Oprations

In [92]:
M1 = np.arange(1,5).reshape(2,2)
M2 = np.arange(5,9).reshape(2,2)

In [93]:
M1

array([[1, 2],
       [3, 4]])

In [94]:
M2

array([[5, 6],
       [7, 8]])

In [97]:
mul = M1@M2
mul

array([[19, 22],
       [43, 50]])

In [98]:
mul = np.dot(M1,M2)
mul

array([[19, 22],
       [43, 50]])

In [99]:
M1

array([[1, 2],
       [3, 4]])

In [101]:
 M1.T

array([[1, 3],
       [2, 4]])

Advance Array Manipulation

1.Stacking Array

In [105]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [108]:
b = np.arange(6,11)
b

array([ 6,  7,  8,  9, 10])

In [115]:
v_stack = np.vstack((a,b))
v_stack

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [116]:
h_stack = np.hstack((a,b))
h_stack

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
col_stack = np.column_stack((a,b))
col_stack

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

2. Splitting Array

In [118]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [121]:
c1 = np.hsplit(c,4)
c1

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [124]:
c1 = np.hsplit(c,2)
c1

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [126]:
c1 = np.vsplit(c,2)
c1

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [127]:
c1 = np.vsplit(c,4)
c1

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]