Valid Sudoku

In [207]:
import numpy as np

In [208]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [209]:
a = np.sum(s, axis = 1)
a

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [210]:
b = np.sum(s, axis = 0)
b

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [211]:
c = a + b
c

array([90, 90, 90, 90, 90, 90, 90, 90, 90])

In [212]:
for i in c:
    if (i != 90):
        print("Sudoku is Invalid")
        break
else:
    print("Sudoku is Valid")
        

Sudoku is Valid


In [213]:
b1_col = np.sum(s[0:3,0:3],axis = 0)
b1_col

array([12, 19, 14])

In [214]:
b1_row = np.sum(s[0:3,0:3],axis = 1)
b1_row

array([12, 15, 18])

In [215]:
b11 = np.sum(b1_row)
b11

np.int64(45)

In [216]:
b12 = np.sum(b1_col)
b12

np.int64(45)

In [217]:
b11_b12 = b11+b12
b11_b12

np.int64(90)

In [218]:
if(b11_b12 == 90):
    print("Valid")
else:
    print("Invalid")

Valid


In [219]:
for i in range(0,9,3):
    for j in range(0,9,3):
        p = (s[i:i+3,j:j+3])
        l = p.sum()
        print(l==45)

True
True
True
True
True
True
True
True
True
